version: "3"

services:
  postgres:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    volumes:
      - ${HOME}/auth-postgres-data/:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "80:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.local
      - PGADMIN_DEFAULT_PASSWORD=SuperSecret
